Api task
stepanstefan/92-Microservices pull request #2
Opened 2022-11-28 14:17 UTC by stepanstefan

2022-11-30 10:48 UTC, afterbvrner requested changes
Не хватает части методов (помещение товара в корзину, например), доставкой занимается delivery service. В общем, сверьтесь ещё раз с https://github.com/microservices-itmo-21-22/system_api

2022-11-30 10:48 UTC, afterbvrner commented on src/main/kotlin/com/itmo/microservices/demo/order/api/model/DeliverySlot.kt
> +data class DeliverySlot @JsonCreator constructor(
Для единственного конструктора не нужен JsonCreator

2022-11-30 10:48 UTC, maxgolish commented on src/main/kotlin/com/itmo/microservices/demo/order/api/controller/OrderController.kt
> +    @PostMapping("/payment/{orderId}/deliverySlot")
/orders/{order_id}/delivery?slot={slot_in_sec}

2022-11-30 10:48 UTC, afterbvrner commented on src/main/kotlin/com/itmo/microservices/demo/order/api/controller/OrderController.kt
> +    @PostMapping
На создание должен быть /orders, не /order

2022-11-30 10:48 UTC, maxgolish commented on src/main/kotlin/com/itmo/microservices/demo/order/api/controller/OrderController.kt
> +    @PostMapping("/payment/{orderId}")
/orders/{order_id}/payment

2022-11-30 14:28 UTC, stepanstefan commented on src/main/kotlin/com/itmo/microservices/demo/order/api/model/DeliverySlot.kt
> +data class DeliverySlot @JsonCreator constructor(
Где то читал, что в случае отсутствия джексон может сетить поля через сеттеры или вообще через рефлексию. Если найду - отправлю сюда. Если не найду - поправлю.

2022-12-04 20:05 UTC, stepanstefan commented
@afterbvrner я думал, что нужно делать по нашему API, который мы делали в рамках одного из спринтов. Ошибся. Переделал под общий формат.

2022-12-04 20:05 UTC, stepanstefan commented on src/main/kotlin/com/itmo/microservices/demo/order/api/model/DeliverySlot.kt
> +data class DeliverySlot @JsonCreator constructor(
Посмотрел исходники Джексона - ошибся.

2022-12-05 17:12 UTC, afterbvrner approved these changes

2022-12-05 17:12 UTC, afterbvrner commented on src/main/kotlin/com/itmo/microservices/demo/order/api/model/BookingDto.kt
> +    val id: UUID = UUID.randomUUID(),
Без дефолтного значения

2022-12-05 17:12 UTC, afterbvrner commented on src/main/kotlin/com/itmo/microservices/demo/order/api/model/OrderDto.kt
> +    var id: UUID = UUID.randomUUID(),
Не нужен дефолтный для ID

2022-12-05 17:26 UTC, merged